default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: develop
  password: develop
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: simplero_social_development
test:
  <<: *default
  database: simplero_social_test
production:
  <<: *default
  database: ddaeef0ert2nt2
  host: <%= Rails.application.credentials.database[:host] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
